CREATE OR REPLACE PROCEDURE drop_database()
AS $$
BEGIN
    DROP PROCEDURE IF EXISTS add_company(VARCHAR(50), VARCHAR(50), VARCHAR(100), VARCHAR(50), VARCHAR(50), VARCHAR(50), VARCHAR(15)) CASCADE;
    DROP PROCEDURE IF EXISTS update_company(VARCHAR(50), VARCHAR(50), VARCHAR(100), VARCHAR(50), VARCHAR(50), VARCHAR(50), VARCHAR(15)) CASCADE;
    DROP PROCEDURE IF EXISTS delete_company(VARCHAR(50)) CASCADE;
    DROP PROCEDURE IF EXISTS add_staff(VARCHAR(50), VARCHAR(50), VARCHAR(50), VARCHAR(50), VARCHAR(50), VARCHAR(50), VARCHAR(50), VARCHAR(50)) CASCADE;
    DROP FUNCTION IF EXISTS get_department_staff(VARCHAR(50), VARCHAR(50)) CASCADE;
    DROP PROCEDURE IF EXISTS add_hardware(VARCHAR(50), TEXT) CASCADE;
    DROP PROCEDURE IF EXISTS add_request(INTEGER, VARCHAR(50), VARCHAR(50), TEXT) CASCADE;
    DROP PROCEDURE IF EXISTS add_task(TEXT, INTEGER, VARCHAR(50), INTEGER) CASCADE;
    DROP PROCEDURE IF EXISTS reassign_tasks(VARCHAR(50), VARCHAR(50)) CASCADE;
    
    DROP TABLE IF EXISTS Tasks CASCADE;
    DROP TABLE IF EXISTS Requests CASCADE;
    DROP TABLE IF EXISTS Hardware CASCADE;
    DROP TABLE IF EXISTS Staff CASCADE;
    DROP TABLE IF EXISTS Contracts CASCADE;
    DROP TABLE IF EXISTS Companies CASCADE;
    
    DROP ROLE IF EXISTS administrator;
    DROP ROLE IF EXISTS company;
    DROP ROLE IF EXISTS worker;
    DROP ROLE IF EXISTS executive;
    DROP ROLE IF EXISTS distributor;
    
    DROP PROCEDURE IF EXISTS create_database() CASCADE;
    DROP PROCEDURE IF EXISTS create_requests() CASCADE;
    DROP PROCEDURE IF EXISTS create_roles() CASCADE;
    
    RAISE NOTICE 'Database dropped.';
END;
$$ LANGUAGE plpgsql;
