SET CONSTRAINTS ALL DEFERRED;

DELETE FROM Tasks;
DELETE FROM Requests;
DELETE FROM Transport;
DELETE FROM Positions;
DELETE FROM Hardware;
DELETE FROM Staff;
DELETE FROM Companies;
DELETE FROM Contracts;

ALTER SEQUENCE hardware_id_seq RESTART WITH 1;
ALTER SEQUENCE positions_id_seq RESTART WITH 1;

SET CONSTRAINTS ALL IMMEDIATE;
